-- Cmd: createdb extrasolar
CREATE TABLE
  stars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(25) NOT NULL UNIQUE,
    distance integer NOT NULL CHECK (distance > 0),
    spectral_type char(1),
    companions integer NOT NULL CHECK (companions >= 0)
  );

CREATE TABLE
  planets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation char(1) UNIQUE,
    mass integer
  );

-- Cmd: dpsql -d extrasolar < 01_create_extrasolar_planetary_db.sql