CREATE TABLE
  moons (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation integer NOT NULL CHECK (designation > 0),
    semi_major_axis numeric CHECK (semi_major_axis > 0.0),
    mass numeric CHECK (mass > 0.0),
    planet_id bigint REFERENCES planets (id)
  );

-- `planets` to `moons` relationship has a cardinality of one-to-many and a
-- modality of 0 (0 moons required)